import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');
export const GRID_SPACING = 8;
export const GRID_COLUMNS = 2;
export const GRID_ITEM_WIDTH = (SCREEN_WIDTH - 32 - GRID_SPACING * (GRID_COLUMNS - 1)) / GRID_COLUMNS;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  safeArea: {
    flex: 1,
  },
  keyboardView: {
    flex: 1,
  },
  headerButton: {
    padding: 8,
    marginLeft: Platform.OS === 'ios' ? 0 : 8,
  },
  headerRight: {
    flexDirection: 'row',
    gap: 4,
    marginRight: Platform.OS === 'ios' ? 0 : 8,
  },
  viewModeBtn: {
    padding: 8,
    borderRadius: 6,
  },
  viewModeBtnActive: {
    backgroundColor: 'rgba(0,255,136,0.15)',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.5)',
  },
  header: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.1)',
    gap: 12,
  },
  headerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: '#ffffff',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#ffffff',
    paddingVertical: 0,
  },
  importSection: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    backgroundColor: 'rgba(0,255,136,0.05)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,255,136,0.25)',
  },
  importHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  importTitle: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#ffffff',
  },
  importRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  importInput: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#ffffff',
  },
  importButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#00aaff',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  importButtonDisabled: {
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  importButtonText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#ffffff',
  },
  importButtonTextDisabled: {
    color: 'rgba(255,255,255,0.4)',
  },
  importActionsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  importActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(0,255,136,0.1)',
    borderRadius: 8,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,255,136,0.3)',
    borderStyle: 'dashed',
  },
  importActionButtonDisabled: {
    opacity: 0.6,
  },
  importActionButtonText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#00ff88',
  },
  importHint: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.4)',
    marginTop: 8,
    textAlign: 'center' as const,
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  emptyIcon: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: '600' as const,
    color: '#ffffff',
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.5)',
    textAlign: 'center' as const,
    lineHeight: 20,
    marginBottom: 24,
  },
  emptyHints: {
    gap: 12,
    marginBottom: 32,
  },
  hintItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 10,
  },
  hintText: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.7)',
  },
  gridContent: {
    padding: 16,
  },
  gridWrapper: {
    justifyContent: 'space-between',
    gap: GRID_SPACING,
  },
  gridItem: {
    width: GRID_ITEM_WIDTH,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  gridItemSelected: {
    borderColor: '#00ff88',
    backgroundColor: 'rgba(0,255,136,0.08)',
  },
  gridThumbnail: {
    width: '100%',
    aspectRatio: 9 / 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    position: 'relative',
  },
  gridThumbnailImage: {
    width: '100%',
    height: '100%',
  },
  gridThumbnailPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 6,
  },
  gridTypeBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,0,0,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  portraitBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(0,255,136,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  aspectRatioBadge: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  aspectRatioText: {
    fontSize: 9,
    fontWeight: '600' as const,
    color: '#ffffff',
  },
  gridSelectedOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,255,136,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridInfo: {
    padding: 10,
  },
  gridName: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#ffffff',
  },
  gridMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  gridMetaText: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.4)',
  },
  gridMetaDot: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.2)',
    marginHorizontal: 4,
  },
  gridActions: {
    flexDirection: 'row',
    padding: 10,
    paddingTop: 0,
    gap: 6,
  },
  gridUseBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#00ff88',
    paddingVertical: 8,
    borderRadius: 8,
  },
  gridUseBtnText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#0a0a0a',
  },
  gridActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(0,170,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gridDeleteBtn: {
    backgroundColor: 'rgba(255,68,68,0.15)',
  },
  gridCheckBtn: {
    backgroundColor: 'rgba(0,255,136,0.15)',
  },
  listContent: {
    padding: 16,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  listItemSelected: {
    borderColor: '#00ff88',
    backgroundColor: 'rgba(0,255,136,0.08)',
  },
  listThumbnail: {
    width: 56,
    height: 100,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.1)',
    overflow: 'hidden',
    position: 'relative',
  },
  listThumbnailImage: {
    width: '100%',
    height: '100%',
  },
  listThumbnailPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  listTypeBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(0,0,0,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  listInfo: {
    flex: 1,
    marginLeft: 12,
  },
  listName: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#ffffff',
  },
  listOriginalName: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.4)',
    marginTop: 2,
  },
  listMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 6,
    flexWrap: 'wrap',
  },
  listMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  listMetaText: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.4)',
  },
  listActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginLeft: 8,
  },
  listSelectHint: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.3)',
    paddingHorizontal: 8,
  },
  listUseBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#00ff88',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  listUseBtnText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: '#0a0a0a',
  },
  listDeleteBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(255,68,68,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  listCheckBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(0,255,136,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  listFooter: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.3)',
  },
});
